/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#001b3c',
        'surface-container-lowest': '#0d0d1c',
        'error-container': '#93000a',
        'surface-variant': '#333344',
        'surface-container-highest': '#333344',
        'inverse-on-surface': '#2f2f40',
        'on-tertiary': '#3a2e2b',
        'surface-tint': '#d9b9ff',
        'on-background': '#e3e0f7',
        'on-secondary': '#003062',
        'on-tertiary-container': '#524442',
        'surface-dim': '#121221',
        'on-primary-fixed-variant': '#57377f',
        'surface-container': '#1e1e2e',
        'tertiary-container': '#c5b2ae',
        'on-primary': '#3f1e66',
        'primary-fixed-dim': '#d9b9ff',
        'inverse-primary': '#704f98',
        'on-surface-variant': '#cdc3d1',
        'on-tertiary-fixed-variant': '#514441',
        'surface-container-low': '#1a1a2a',
        secondary: '#a8c8ff',
        outline: '#968e9a',
        'outline-variant': '#4a444f',
        error: '#ffb4ab',
        success: '#7defa1',
        surface: '#121221',
        'on-secondary-container': '#8fbaff',
        'primary-fixed': '#eedbff',
        'surface-bright': '#383849',
        'on-surface': '#e3e0f7',
        'tertiary-fixed': '#f3deda',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#241917',
        'secondary-fixed': '#d5e3ff',
        'on-error': '#690005',
        background: '#121221',
        'on-primary-container': '#57377f',
        'primary-container': '#cba6f7',
        'secondary-fixed-dim': '#a8c8ff',
        tertiary: '#e2cdc9',
        'surface-container-high': '#292839',
        'tertiary-fixed-dim': '#d6c2be',
        'secondary-container': '#124988',
        'inverse-surface': '#e3e0f7',
        'on-primary-fixed': '#290350',
        primary: '#e2c7ff',
        'on-secondary-fixed-variant': '#0e4685',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
