import type { ThemeDefinition } from '../../types'
import { gruvboxPalette } from './palette'

const { bright, dark, neutral } = gruvboxPalette

export const gruvboxDark: ThemeDefinition = {
  id: 'gruvbox-dark',
  label: 'Gruvbox Dark',
  kind: 'dark',
  ui: {
    surface: dark.bg0,
    'surface-container-lowest': dark.bg0Hard,
    'surface-container-low': dark.bg1,
    'surface-container': dark.bg2,
    'surface-container-high': dark.bg3,
    'surface-container-highest': dark.bg4,
    'surface-bright': dark.bg3,
    'surface-tint': bright.orange,
    'browser-bar': dark.bg0Hard,
    'browser-tab-active': dark.bg1,
    primary: bright.orange,
    'primary-container': neutral.orange,
    'primary-dim': '#f57c1f',
    'primary-deep': '#a3490d',
    'on-primary': dark.bg0Hard,
    secondary: bright.blue,
    'secondary-container': neutral.blue,
    'secondary-dim': '#6f8f88',
    'on-secondary': dark.fg1,
    'on-secondary-container': dark.fg1,
    tertiary: bright.purple,
    'tertiary-container': neutral.purple,
    'on-tertiary': dark.bg0Hard,
    'on-tertiary-container': dark.fg1,
    error: bright.red,
    'error-container': neutral.red,
    'error-dim': '#e04431',
    'on-error': dark.bg0Hard,
    'on-error-container': dark.fg1,
    success: bright.green,
    'success-muted': neutral.green,
    warning: bright.yellow,
    'on-surface': dark.fg1,
    'on-surface-variant': dark.fg2,
    'on-surface-muted': dark.gray,
    outline: dark.bg4,
    'outline-variant': dark.bg3,
    'editor-fg': dark.fg1,
    'editor-fg-dim': dark.fg4,
    'vcs-modified': bright.yellow,
    'vcs-added': bright.green,
    'vcs-deleted': bright.red,
    'vcs-renamed': bright.aqua,
    'vcs-untracked': bright.purple,
  },
  effects: {
    'glass-fill': 'rgba(40, 40, 40, 0.88)',
    selection: 'rgba(254, 128, 25, 0.24)',
    'scrollbar-thumb': dark.bg3,
    'scrollbar-thumb-hover': dark.bg4,
    'diff-added': 'rgba(184, 187, 38, 0.15)',
    'diff-removed': 'rgba(251, 73, 52, 0.15)',
    'diff-highlight-added': 'rgba(184, 187, 38, 0.35)',
    'diff-highlight-removed': 'rgba(251, 73, 52, 0.35)',
    'wash-faint': 'rgba(255, 255, 255, 0.04)',
    'wash-subtle': 'rgba(255, 255, 255, 0.05)',
    'wash-soft': 'rgba(255, 255, 255, 0.08)',
    scrim: '#000000',
  },
  shadows: {
    'pane-focus':
      '0 0 0 6px rgb(254 128 25 / 0.16), 0 8px 32px rgb(0 0 0 / 0.35)',
    modal: '0 24px 80px rgb(0 0 0 / 0.5)',
    'pip-glow': '0 0 4px currentColor',
    ambient: '0 10px 40px rgba(0, 0, 0, 0.4)',
    'glow-primary': '0 0 24px rgba(254, 128, 25, 0.35)',
    'ring-primary': '0 0 0 3px rgba(254, 128, 25, 0.28)',
  },
  syntax: {
    keyword: bright.red,
    string: bright.green,
    fn: bright.aqua,
    variable: bright.blue,
    comment: dark.gray,
    type: bright.yellow,
    tag: bright.aqua,
    class: bright.yellow,
    operator: bright.orange,
  },
  terminal: {
    foreground: dark.fg1,
    background: dark.bg0,
    cursor: dark.fg1,
    cursorAccent: dark.bg0,
    selectionBackground: dark.bg2,
    black: dark.bg0,
    red: neutral.red,
    green: neutral.green,
    yellow: neutral.yellow,
    blue: neutral.blue,
    magenta: neutral.purple,
    cyan: neutral.aqua,
    white: dark.fg4,
    brightBlack: dark.gray,
    brightRed: bright.red,
    brightGreen: bright.green,
    brightYellow: bright.yellow,
    brightBlue: bright.blue,
    brightMagenta: bright.purple,
    brightCyan: bright.aqua,
    brightWhite: dark.fg1,
  },
  agents: {
    claude: {
      accent: bright.purple,
      accentDim: 'rgb(211 134 155 / 0.16)',
      accentSoft: 'rgb(211 134 155 / 0.32)',
      onAccent: dark.bg0Hard,
    },
    codex: {
      accent: bright.green,
      accentDim: 'rgb(184 187 38 / 0.16)',
      accentSoft: 'rgb(184 187 38 / 0.32)',
      onAccent: dark.bg0Hard,
    },
    shell: {
      accent: bright.yellow,
      accentDim: 'rgb(250 189 47 / 0.14)',
      accentSoft: 'rgb(250 189 47 / 0.3)',
      onAccent: dark.bg0Hard,
    },
    browser: {
      accent: bright.aqua,
      accentDim: 'rgb(142 192 124 / 0.16)',
      accentSoft: 'rgb(142 192 124 / 0.3)',
      onAccent: dark.bg0Hard,
    },
    kimi: {
      accent: bright.orange,
      accentDim: 'rgb(254 128 25 / 0.16)',
      accentSoft: 'rgb(254 128 25 / 0.32)',
      onAccent: dark.bg0Hard,
    },
    opencode: {
      accent: bright.blue,
      accentDim: 'rgb(131 165 152 / 0.16)',
      accentSoft: 'rgb(131 165 152 / 0.32)',
      onAccent: dark.bg0Hard,
    },
  },
}
