import type { ThemeDefinition } from '../../types'
import { gruvboxPalette } from './palette'

const { faded, light, neutral } = gruvboxPalette

export const gruvboxLight: ThemeDefinition = {
  id: 'gruvbox-light',
  label: 'Gruvbox Light',
  kind: 'light',
  ui: {
    surface: light.bg0Hard,
    'surface-container-lowest': light.bg1,
    'surface-container-low': light.bg2,
    'surface-container': light.bg3,
    'surface-container-high': '#b7aa8f',
    'surface-container-highest': '#b4a78d',
    'surface-bright': '#b0a48a',
    'surface-tint': faded.orange,
    'browser-bar': '#f1e6bd',
    'browser-tab-active': '#f6edc8',
    primary: faded.orange,
    'primary-container': neutral.orange,
    'primary-dim': '#c24b08',
    'primary-deep': '#7c2d00',
    'on-primary': light.bg0,
    secondary: faded.blue,
    'secondary-container': neutral.blue,
    'secondary-dim': '#2e7680',
    'on-secondary': light.bg0,
    'on-secondary-container': light.bg0,
    tertiary: faded.purple,
    'tertiary-container': neutral.purple,
    'on-tertiary': light.bg0,
    'on-tertiary-container': light.bg0,
    error: neutral.red,
    'error-container': faded.red,
    'error-dim': '#b51211',
    'on-error': light.bg0,
    'on-error-container': light.bg0,
    success: faded.green,
    'success-muted': neutral.green,
    warning: faded.yellow,
    'on-surface': light.fg0,
    'on-surface-variant': light.fg1,
    'on-surface-muted': light.gray,
    outline: light.fg4,
    'outline-variant': light.bg4,
    'editor-fg': light.fg0,
    'editor-fg-dim': light.fg4,
    'vcs-modified': faded.yellow,
    'vcs-added': faded.green,
    'vcs-deleted': faded.red,
    'vcs-renamed': faded.aqua,
    'vcs-untracked': faded.purple,
  },
  effects: {
    'glass-fill': 'rgba(251, 241, 199, 0.88)',
    selection: 'rgba(175, 58, 3, 0.24)',
    'scrollbar-thumb': light.bg2,
    'scrollbar-thumb-hover': light.bg4,
    'diff-added': 'rgba(121, 116, 14, 0.14)',
    'diff-removed': 'rgba(157, 0, 6, 0.12)',
    'diff-highlight-added': 'rgba(121, 116, 14, 0.3)',
    'diff-highlight-removed': 'rgba(157, 0, 6, 0.28)',
    'wash-faint': 'rgba(16, 15, 15, 0.04)',
    'wash-subtle': 'rgba(16, 15, 15, 0.05)',
    'wash-soft': 'rgba(16, 15, 15, 0.08)',
    scrim: '#000000',
  },
  shadows: {
    'pane-focus':
      '0 0 0 6px rgb(175 58 3 / 0.14), 0 8px 24px rgb(40 40 40 / 0.12)',
    modal: '0 24px 60px rgb(40 40 40 / 0.18)',
    'pip-glow': '0 0 4px currentColor',
    ambient: '0 10px 30px rgba(40, 40, 40, 0.12)',
    'glow-primary': '0 0 24px rgba(175, 58, 3, 0.2)',
    'ring-primary': '0 0 0 3px rgba(175, 58, 3, 0.25)',
  },
  syntax: {
    keyword: faded.red,
    string: faded.green,
    fn: faded.aqua,
    variable: faded.blue,
    comment: light.gray,
    type: faded.yellow,
    tag: faded.aqua,
    class: faded.yellow,
    operator: faded.orange,
  },
  terminal: {
    foreground: light.fg1,
    background: light.bg0,
    cursor: light.fg1,
    cursorAccent: light.bg0,
    selectionBackground: light.bg2,
    black: light.bg0,
    red: neutral.red,
    green: neutral.green,
    yellow: neutral.yellow,
    blue: neutral.blue,
    magenta: neutral.purple,
    cyan: neutral.aqua,
    white: light.fg4,
    brightBlack: light.gray,
    brightRed: faded.red,
    brightGreen: faded.green,
    brightYellow: faded.yellow,
    brightBlue: faded.blue,
    brightMagenta: faded.purple,
    brightCyan: faded.aqua,
    brightWhite: light.fg1,
  },
  agents: {
    claude: {
      accent: faded.purple,
      accentDim: 'rgb(143 63 113 / 0.14)',
      accentSoft: 'rgb(143 63 113 / 0.28)',
      onAccent: light.bg0,
    },
    codex: {
      accent: neutral.green,
      accentDim: 'rgb(152 151 26 / 0.14)',
      accentSoft: 'rgb(152 151 26 / 0.28)',
      onAccent: light.fg0,
    },
    shell: {
      accent: faded.yellow,
      accentDim: 'rgb(181 118 20 / 0.14)',
      accentSoft: 'rgb(181 118 20 / 0.28)',
      onAccent: light.fg0,
    },
    browser: {
      accent: neutral.aqua,
      accentDim: 'rgb(104 157 106 / 0.14)',
      accentSoft: 'rgb(104 157 106 / 0.28)',
      onAccent: light.fg0,
    },
    kimi: {
      accent: neutral.orange,
      accentDim: 'rgb(214 93 14 / 0.14)',
      accentSoft: 'rgb(214 93 14 / 0.28)',
      onAccent: light.fg0,
    },
    opencode: {
      accent: faded.blue,
      accentDim: 'rgb(7 102 120 / 0.14)',
      accentSoft: 'rgb(7 102 120 / 0.28)',
      onAccent: light.bg0,
    },
  },
}
