//! Statusline bridge file generation
//!
//! Generates per-session statusline scripts and settings files that allow
//! Claude Code (or other agents) to write statusline JSON to a known location
//! for Vimeflow's file watcher to pick up.

use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

/// Result of generating statusline bridge files
#[derive(Debug, Clone)]
#[allow(dead_code)] // Fields read by spawn_pty and future cleanup logic
pub struct BridgeFiles {
    /// Path to the generated statusline script
    pub script_path: PathBuf,
    /// Path to the generated settings.json
    pub settings_path: PathBuf,
    /// Path to the status.json file that the script writes to
    pub status_file_path: PathBuf,
    /// Path to the shell init script that wraps `claude` with --settings
    pub shell_init_path: PathBuf,
    /// Path to generated zsh environment file used when the user's shell is zsh
    pub zsh_env_path: PathBuf,
    /// Path to generated zsh rc file used when the user's shell is zsh
    pub zsh_rc_path: PathBuf,
}

/// Generate the statusline bridge files for a session.
///
/// Creates:
/// 1. `<dir>/statusline.sh` — receives JSON on stdin, writes to `status.json`
/// 2. `<dir>/settings.json` — Claude Code settings overlay pointing to the script
///
/// # Arguments
/// * `agent_status_dir` - Directory to create files in (e.g. `.vimeflow/sessions/<id>/`)
/// * `session_id` - Session identifier for the comment header
///
/// # Returns
/// * `Ok(BridgeFiles)` with paths to generated files
/// * `Err(String)` if directory creation or file writing fails
pub fn generate_bridge_files(
    agent_status_dir: &str,
    session_id: &str,
) -> Result<BridgeFiles, String> {
    let dir = Path::new(agent_status_dir);

    // Create the session directory
    fs::create_dir_all(dir)
        .map_err(|e| format!("failed to create agent status directory: {}", e))?;

    let script_path = dir.join("statusline.sh");
    let settings_path = dir.join("settings.json");
    let status_file_path = dir.join("status.json");
    let shell_init_path = dir.join("init.sh");
    let zsh_env_path = dir.join(".zshenv");
    let zsh_rc_path = dir.join(".zshrc");

    // Generate the statusline script. The path is passed via env var
    // (VIMEFLOW_STATUS_FILE) set by spawn_pty — avoids embedding paths
    // in the script which breaks if CWD contains quotes or metacharacters.
    let script_content = format!(
        "#!/usr/bin/env bash\n\
         # Auto-generated by Vimeflow for session {session_id}\n\
         # Receives Claude Code statusline JSON on stdin, writes to status file\n\
         cat > \"$VIMEFLOW_STATUS_FILE\"\n",
        session_id = session_id,
    );

    fs::write(&script_path, &script_content)
        .map_err(|e| format!("failed to write statusline script: {}", e))?;

    // Make script executable (rwxr-xr-x)
    // Make script executable on Unix (no-op on Windows — scripts aren't used there)
    #[cfg(unix)]
    fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755))
        .map_err(|e| format!("failed to set script permissions: {}", e))?;

    // Generate the settings.json overlay using serde_json for proper escaping
    let settings = serde_json::json!({
        "statusLine": {
            "type": "command",
            "command": script_path.to_string_lossy(),
            "refreshInterval": 5
        }
    });
    fs::write(
        &settings_path,
        serde_json::to_string_pretty(&settings)
            .map_err(|e| format!("failed to serialize settings: {}", e))?,
    )
    .map_err(|e| format!("failed to write settings.json: {}", e))?;

    // Generate shell init script that wraps `claude` with --settings.
    // Must unalias first — if the user has `alias claude='... claude ...'`,
    // bash expands the alias during function definition and produces a
    // syntax error (e.g., `NO_FLICKER=1 claude --skip-perms() {`).
    // The settings path is passed via env var (VIMEFLOW_CLAUDE_SETTINGS)
    // set by spawn_pty — avoids embedding paths that may contain quotes.
    let shell_init_content = format!(
        "# Auto-generated by Vimeflow for session {session_id}\n\
         # Wraps claude with --settings to inject statusline bridge config\n\
         unalias claude 2>/dev/null\n\
         claude() {{ command claude --settings \"$VIMEFLOW_CLAUDE_SETTINGS\" \"$@\"; }}\n",
        session_id = session_id,
    );

    fs::write(&shell_init_path, &shell_init_content)
        .map_err(|e| format!("failed to write shell init script: {}", e))?;

    // zsh does not read BASH_ENV. macOS defaults to zsh, so give spawned zsh
    // sessions a private ZDOTDIR that preserves user startup files from HOME
    // and then installs the Claude wrapper.
    let zsh_env_content = format!(
        "# Auto-generated by Vimeflow for session {session_id}\n\
         [ -f \"$HOME/.zshenv\" ] && source \"$HOME/.zshenv\"\n\
         [ -n \"$VIMEFLOW_AGENT_INIT\" ] && source \"$VIMEFLOW_AGENT_INIT\"\n",
        session_id = session_id,
    );
    fs::write(&zsh_env_path, &zsh_env_content)
        .map_err(|e| format!("failed to write zsh env script: {}", e))?;

    let zsh_rc_content = format!(
        "# Auto-generated by Vimeflow for session {session_id}\n\
         [ -f \"$HOME/.zshrc\" ] && source \"$HOME/.zshrc\"\n\
         [ -n \"$VIMEFLOW_AGENT_INIT\" ] && source \"$VIMEFLOW_AGENT_INIT\"\n",
        session_id = session_id,
    );
    fs::write(&zsh_rc_path, &zsh_rc_content)
        .map_err(|e| format!("failed to write zsh rc script: {}", e))?;

    log::info!(
        "Generated statusline bridge for session {}: {}",
        session_id,
        dir.display()
    );

    Ok(BridgeFiles {
        script_path,
        settings_path,
        status_file_path,
        shell_init_path,
        zsh_env_path,
        zsh_rc_path,
    })
}

/// Clean up statusline bridge files for a session.
///
/// Removes the entire session directory if it exists.
#[allow(dead_code)] // Will be used by session cleanup in future sub-spec
pub fn cleanup_bridge_files(agent_status_dir: &str) -> Result<(), String> {
    let dir = Path::new(agent_status_dir);
    if dir.exists() {
        fs::remove_dir_all(dir).map_err(|e| format!("failed to clean up bridge files: {}", e))?;
        log::info!("Cleaned up bridge files: {}", dir.display());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[cfg(unix)]
    use std::io::Write;
    #[cfg(unix)]
    use std::os::unix::fs::PermissionsExt;
    #[cfg(unix)]
    use std::process::{Command, Stdio};

    #[test]
    fn generates_bridge_files_in_temp_dir() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let dir = tmp.path().join("session-abc");

        let result = generate_bridge_files(dir.to_str().unwrap(), "session-abc");
        assert!(result.is_ok(), "generate_bridge_files should succeed");

        let files = result.unwrap();

        // Script should exist and be executable
        assert!(files.script_path.exists());
        assert!(files.zsh_env_path.exists());
        assert!(files.zsh_rc_path.exists());
        #[cfg(unix)]
        {
            let meta = fs::metadata(&files.script_path).unwrap();
            assert!(
                meta.permissions().mode() & 0o111 != 0,
                "script should be executable"
            );
        }

        // Script content should reference env var for status file
        let script = fs::read_to_string(&files.script_path).unwrap();
        assert!(script.contains("session-abc"));
        assert!(script.contains("VIMEFLOW_STATUS_FILE"));

        let zsh_env = fs::read_to_string(&files.zsh_env_path).unwrap();
        assert!(zsh_env.contains("VIMEFLOW_AGENT_INIT"));

        // Settings should exist and contain statusLine config
        assert!(files.settings_path.exists());
        let settings = fs::read_to_string(&files.settings_path).unwrap();
        assert!(settings.contains("statusLine"));
        assert!(settings.contains("statusline.sh"));
        assert!(settings.contains("refreshInterval"));
    }

    #[test]
    fn creates_nested_directories() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let dir = tmp.path().join("deep").join("nested").join("session-xyz");

        let result = generate_bridge_files(dir.to_str().unwrap(), "session-xyz");
        assert!(result.is_ok());
        assert!(dir.exists());
    }

    #[cfg(unix)]
    #[test]
    fn statusline_script_writes_status_file_with_quoted_path_chars() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let dir = tmp.path().join("space dir").join("quote's session");

        let files = generate_bridge_files(dir.to_str().unwrap(), "session-quoted")
            .expect("generate bridge files");
        let status_json = r#"{"session_id":"session-quoted","transcript_path":null}"#;
        let mut child = Command::new(&files.script_path)
            .env("VIMEFLOW_STATUS_FILE", &files.status_file_path)
            .stdin(Stdio::piped())
            .spawn()
            .expect("spawn statusline script");

        child
            .stdin
            .as_mut()
            .expect("statusline stdin")
            .write_all(status_json.as_bytes())
            .expect("write status payload");

        let status = child.wait().expect("wait for statusline script");
        assert!(status.success(), "statusline script should exit cleanly");

        let written = fs::read_to_string(&files.status_file_path)
            .expect("statusline script should write status file");
        assert_eq!(written, status_json);
    }

    #[cfg(unix)]
    #[test]
    fn shell_init_wraps_claude_with_settings_path_chars() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let dir = tmp.path().join("space dir").join("quote's session");
        let fake_bin = tmp.path().join("bin");
        let calls_path = tmp.path().join("claude-calls.txt");
        fs::create_dir_all(&fake_bin).expect("create fake bin");

        let fake_claude = fake_bin.join("claude");
        fs::write(
            &fake_claude,
            format!(
                "#!/bin/sh\n\
                 printf '%s\\n' \"$*\" >> \"{}\"\n",
                calls_path.display()
            ),
        )
        .expect("write fake claude");
        fs::set_permissions(&fake_claude, fs::Permissions::from_mode(0o755))
            .expect("chmod fake claude");

        let files = generate_bridge_files(dir.to_str().unwrap(), "session-quoted")
            .expect("generate bridge files");
        let path = format!(
            "{}:{}",
            fake_bin.to_string_lossy(),
            std::env::var("PATH").unwrap_or_default()
        );
        let status = Command::new("bash")
            .arg("-c")
            .arg("source \"$BASH_ENV\" && claude --model sonnet --print ok")
            .env("PATH", path)
            .env("BASH_ENV", &files.shell_init_path)
            .env("VIMEFLOW_CLAUDE_SETTINGS", &files.settings_path)
            .status()
            .expect("run shell init");

        assert!(status.success(), "shell init should execute cleanly");

        let calls = fs::read_to_string(&calls_path).expect("fake claude should be invoked");
        assert_eq!(
            calls.trim(),
            format!(
                "--settings {} --model sonnet --print ok",
                files.settings_path.display()
            )
        );
    }

    #[cfg(unix)]
    #[test]
    fn zsh_startup_wraps_claude_with_settings_path_chars() {
        if Command::new("zsh").arg("--version").status().is_err() {
            return;
        }

        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let home = tmp.path().join("home without zsh files");
        let dir = tmp.path().join("space dir").join("quote's session");
        let fake_bin = tmp.path().join("bin");
        let calls_path = tmp.path().join("claude-calls.txt");
        fs::create_dir_all(&home).expect("create fake home");
        fs::create_dir_all(&fake_bin).expect("create fake bin");

        let fake_claude = fake_bin.join("claude");
        fs::write(
            &fake_claude,
            format!(
                "#!/bin/sh\n\
                 printf '%s\\n' \"$*\" >> \"{}\"\n",
                calls_path.display()
            ),
        )
        .expect("write fake claude");
        fs::set_permissions(&fake_claude, fs::Permissions::from_mode(0o755))
            .expect("chmod fake claude");

        let files = generate_bridge_files(dir.to_str().unwrap(), "session-zsh")
            .expect("generate bridge files");
        let path = format!(
            "{}:{}",
            fake_bin.to_string_lossy(),
            std::env::var("PATH").unwrap_or_default()
        );
        let status = Command::new("zsh")
            .arg("-c")
            .arg("claude --model sonnet --print ok")
            .env("HOME", &home)
            .env("PATH", path)
            .env("ZDOTDIR", &dir)
            .env("VIMEFLOW_AGENT_INIT", &files.shell_init_path)
            .env("VIMEFLOW_CLAUDE_SETTINGS", &files.settings_path)
            .status()
            .expect("run zsh wrapper");

        assert!(status.success(), "zsh wrapper should execute cleanly");

        let calls = fs::read_to_string(&calls_path).expect("fake claude should be invoked");
        assert_eq!(
            calls.trim(),
            format!(
                "--settings {} --model sonnet --print ok",
                files.settings_path.display()
            )
        );
    }

    #[test]
    fn cleanup_removes_directory() {
        let tmp = tempfile::tempdir().expect("failed to create temp dir");
        let dir = tmp.path().join("session-cleanup");

        generate_bridge_files(dir.to_str().unwrap(), "session-cleanup").unwrap();
        assert!(dir.exists());

        cleanup_bridge_files(dir.to_str().unwrap()).unwrap();
        assert!(!dir.exists());
    }

    #[test]
    fn cleanup_handles_missing_directory() {
        let result = cleanup_bridge_files("/tmp/nonexistent-vimeflow-dir-12345");
        assert!(
            result.is_ok(),
            "cleanup should succeed for missing directory"
        );
    }
}
