//! Type definitions for terminal PTY operations

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// PTY session identifier (UUID string)
pub type SessionId = String;

/// PTY session metadata returned after spawning
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtySession {
    /// Unique session identifier
    pub id: SessionId,
    /// Process ID of the shell
    pub pid: u32,
    /// Current working directory
    pub cwd: String,
    /// Resolved system shell path used for this PTY.
    pub shell: String,
}

/// Request payload for spawning a new PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SpawnPtyRequest {
    /// Session ID (generated by frontend)
    pub session_id: SessionId,
    /// Current working directory for the shell
    pub cwd: String,
    /// Optional shell path (defaults to system shell)
    #[cfg_attr(test, ts(optional))]
    pub shell: Option<String>,
    /// Optional environment variables
    #[cfg_attr(test, ts(optional))]
    #[cfg_attr(test, ts(type = "Record<string, string>"))]
    pub env: Option<HashMap<String, String>>,
    /// Generate statusline bridge files for agent status tracking
    #[serde(default)]
    pub enable_agent_bridge: bool,
    /// Ephemeral (burner) PTY: skip the session cache and the agent-bridge dir.
    #[serde(default)]
    pub ephemeral: bool,
}

/// Request payload for writing data to a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct WritePtyRequest {
    /// Session ID
    pub session_id: SessionId,
    /// Data to write to PTY stdin
    pub data: String,
}

/// Request payload for resizing a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct ResizePtyRequest {
    /// Session ID
    pub session_id: SessionId,
    /// Terminal rows
    pub rows: u16,
    /// Terminal columns
    pub cols: u16,
}

/// Request payload for killing a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct KillPtyRequest {
    /// Session ID
    pub session_id: SessionId,
}

/// PTY data event payload (emitted to frontend)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyDataEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Output data from PTY stdout (lossy UTF-8 — invalid bytes become U+FFFD)
    pub data: String,
    /// Raw PTY stdout bytes encoded as base64 for byte-preserving renderer
    /// adapters. Existing xterm-compatible renderers continue to use `data`.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub bytes_base64: Option<String>,
    /// Starting byte offset of this chunk in the session's lifetime stream
    pub offset_start: u64,
    /// Raw byte count of this chunk from the PTY read (matches the producer's
    /// offset arithmetic). MUST be used by subscribers to advance their cursor
    /// — never derive cursor advances from `data.len()`, since lossy UTF-8
    /// decoding can replace invalid bytes with U+FFFD (3 bytes when re-encoded)
    /// and shift the cursor away from the producer's offset stream.
    pub byte_len: u64,
}

/// PTY exit event payload (emitted when process exits)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyExitEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Exit code (if available)
    pub code: Option<i32>,
}

/// Burner foreground-state event (emitted when a burner shell's foreground
/// process changes). `running` is true while a foreground command holds the
/// terminal, false when the shell is idle at its prompt or the platform can't
/// introspect the foreground group.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct BurnerForegroundEvent {
    /// Session ID of the burner (ephemeral) PTY
    pub session_id: SessionId,
    /// Whether a foreground command is currently running in the burner shell
    pub running: bool,
}

/// PTY error event payload (emitted on errors)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyErrorEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Error message
    pub message: String,
}

/// Session status — Alive (with replay data) or Exited
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(tag = "kind")]
pub enum SessionStatus {
    Alive {
        pid: u32,
        replay_data: String,
        replay_end_offset: u64,
    },
    Exited {
        last_exit_code: Option<i32>,
    },
}

/// Grouping metadata tying a PTY to its owning frontend workspace session,
/// its position in that session's layout, and its detected agent. Persisted
/// in the session cache (`SessionCacheData.groupings`, keyed by PTY id) and
/// surfaced per-PTY on `SessionInfo` so the frontend can reconstruct the
/// original multi-pane layout on restore instead of fragmenting each PTY into
/// its own single-pane session. `None` for any PTY the frontend never grouped
/// (back-compat: restores as a single-pane session, the pre-grouping behavior).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PaneGrouping {
    /// The frontend `Session.id` (an independent React UUID) this PTY belongs
    /// to. PTYs sharing this value were panes of one workspace session.
    pub workspace_session_id: String,
    /// `LayoutId` of the owning workspace: single|vsplit|hsplit|threeRight|quad.
    pub layout: String,
    /// Stable session baseline cwd — the directory new panes spawn from via
    /// `addPane`. Distinct from each pane's live `info.cwd`: the active
    /// pane's cwd can drift via OSC 7 (e.g. into a worktree subdir) while
    /// the workspace baseline stays at the project root. Persisted in EACH
    /// pane's grouping (denormalised: every pane in one workspace records
    /// the same value) so restore can read it from any pane in the bucket
    /// without a separate workspace-level table. Optional for back-compat
    /// with caches written before this field existed; absent → restore
    /// falls back to deriving from the active pane's cwd.
    #[cfg_attr(test, ts(optional))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workspace_directory: Option<String>,
    /// Session-scoped pane id, e.g. `"p0"`.
    pub pane_id: String,
    /// Stable pane order within the workspace session.
    pub pane_index: u32,
    /// Detected agent CLI: claude-code|codex|aider|generic.
    pub agent_type: String,
    /// Whether this pane is the workspace session's active pane.
    pub active: bool,
}

/// Single session info returned by list_sessions
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SessionInfo {
    pub id: String,
    pub cwd: String,
    #[cfg_attr(test, ts(optional))]
    pub shell: Option<String>,
    pub status: SessionStatus,
    #[cfg_attr(test, ts(optional))]
    #[cfg_attr(test, ts(type = "boolean | null"))]
    pub activity_panel_collapsed: Option<bool>,
    /// Workspace grouping for this PTY, or `None` if it was never grouped.
    /// `skip_serializing_if = "Option::is_none"` omits the field from the
    /// IPC JSON when None instead of emitting `null`, so the generated TS
    /// `grouping?: PaneGrouping` accurately matches the runtime shape —
    /// a consumer that checks for `undefined` will never see a `null`
    /// that the type system claims is `PaneGrouping`.
    #[cfg_attr(test, ts(optional))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grouping: Option<PaneGrouping>,
}

/// Response payload for list_sessions command
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SessionList {
    pub active_session_id: Option<String>,
    pub sessions: Vec<SessionInfo>,
}

/// Request payload for set_active_session command
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
pub struct SetActiveSessionRequest {
    pub id: String,
}

/// Request payload for reorder_sessions command
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
pub struct ReorderSessionsRequest {
    pub ids: Vec<String>,
}

/// Request payload for update_session_cwd command
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
pub struct UpdateSessionCwdRequest {
    pub id: String,
    pub cwd: String,
}

/// Request payload for set_session_activity_panel_collapsed command.
/// `id` is a PTY id — same convention as SetActiveSessionRequest.
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SetSessionActivityPanelCollapsedRequest {
    pub id: String,
    pub collapsed: bool,
}

/// One pane within a workspace session snapshot pushed by the frontend.
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct WorkspacePaneSnapshot {
    /// The PTY id this pane is bound to (frontend `Pane.ptyId`).
    pub pty_id: String,
    /// Session-scoped pane id, e.g. `"p0"`.
    pub pane_id: String,
    /// Stable pane order within the workspace session.
    pub pane_index: u32,
    /// Detected agent CLI: claude-code|codex|aider|generic.
    pub agent_type: String,
    /// Whether this pane is the workspace session's active pane.
    pub active: bool,
}

/// One workspace session (a frontend `Session`) in a grouping snapshot.
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct WorkspaceSessionSnapshot {
    /// The frontend `Session.id` (React UUID).
    pub id: String,
    /// `LayoutId`: single|vsplit|hsplit|threeRight|quad.
    pub layout: String,
    /// Stable session baseline cwd that `addPane` uses for new shells.
    /// Distinct from any pane's live cwd (which can drift via OSC 7).
    /// Optional for back-compat with frontends that haven't yet sent it.
    #[cfg_attr(test, ts(optional))]
    #[serde(default)]
    pub working_directory: Option<String>,
    pub panes: Vec<WorkspacePaneSnapshot>,
}

/// Request payload for set_workspace_sessions — the full current set of
/// workspace sessions and their panes. The backend rebuilds its grouping map
/// from this snapshot (entries for PTYs no longer present are dropped).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SetWorkspaceSessionsRequest {
    pub sessions: Vec<WorkspaceSessionSnapshot>,
}

#[cfg(test)]
mod tests {
    use super::PtyDataEvent;

    #[test]
    fn pty_data_event_serializes_bytes_base64_when_present() {
        let value = serde_json::to_value(PtyDataEvent {
            session_id: "session-1".to_string(),
            data: "��".to_string(),
            bytes_base64: Some("//4=".to_string()),
            offset_start: 0,
            byte_len: 2,
        })
        .expect("serialize event");

        assert_eq!(value["bytesBase64"], "//4=");
    }

    #[test]
    fn pty_data_event_omits_bytes_base64_when_absent() {
        let value = serde_json::to_value(PtyDataEvent {
            session_id: "session-1".to_string(),
            data: "hello".to_string(),
            bytes_base64: None,
            offset_start: 0,
            byte_len: 5,
        })
        .expect("serialize event");

        assert!(value.get("bytesBase64").is_none());
    }
}
