// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentNotificationReason =
  | 'turn-complete'
  | 'approval-requested'
  | 'question-requested'
  | 'agent-error'
