// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallStatus } from './ToolCallStatus'

/**
 * Event emitted when an agent executes a tool call.
 *
 * **Duplication note (PR #302 cycle 13 F2):** during a watcher restart
 * where the new handle's inline-init didn't claim transcript ownership,
 * the OLD transcript tail is signaled-stop under the per-session gate
 * but the actual thread-join happens AFTER gate release (cycle 11 F2,
 * to avoid stalling concurrent gate waiters for ~500ms). In that
 * ≤500ms window before the OLD tail observes its stop flag, the OLD
 * tail may emit one or two more `agent-tool-call` events while the
 * NEW handle is already active. Consumers SHOULD dedup by
 * `tool_use_id` (stable per tool call across both tails). The
 * duplicate window is bounded to one POLL_INTERVAL (500ms) and only
 * occurs at restart boundaries.
 *
 * For `AgentTurnEvent`'s analogous note (no reliable dedup key in the
 * current schema), see that struct's doc.
 */
export type AgentToolCallEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Anthropic tool_use id (e.g., "toolu_01ABC..."). Stable per
   * tool call — used on the frontend as the React key so parallel
   * tool calls sharing a message-level timestamp don't collide.
   * **Also serves as the natural dedup key** for the ≤500ms
   * restart-boundary duplicate window (see struct-level doc).
   */
  toolUseId: string
  /**
   * Tool name (e.g., "Read", "Write", "Bash")
   */
  tool: string
  /**
   * Tool call arguments (JSON string)
   */
  args: string
  /**
   * Execution status
   */
  status: ToolCallStatus
  /**
   * ISO 8601 timestamp
   */
  timestamp: string
  /**
   * Execution duration in milliseconds
   */
  durationMs: bigint
  /**
   * True when this is a Write/Edit on a path that matches a known
   * test-file convention (e.g. `*.test.ts`, `*_test.rs`). Frontend
   * uses this to render the activity feed glyph and verb without
   * needing to glob the path itself.
   */
  isTestFile: boolean
}
