// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when the agent's tracked working directory changes.
 *
 * Sourced from the structured `cwd` field that Claude Code (and Codex,
 * pending follow-up) writes on every transcript JSONL entry. This is the
 * authoritative signal for "where the agent currently is" — it picks up
 * tool-call-driven moves like `EnterWorktree` that intentionally do NOT
 * mutate the interactive shell's `$PWD`, so neither OSC 7 nor PTY text
 * patterns can catch them.
 */
export type AgentCwdEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Absolute working directory the agent reports itself to be in.
   */
  cwd: string
}
