// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentNotificationReason } from './AgentNotificationReason'

export type AgentNotificationEvent = {
  /**
   * PTY session ID. The renderer resolves its owning workspace session.
   */
  ptyId: string
  /**
   * Provider session identity when the live stream exposes it.
   */
  agentSessionId: string | null
  reason: AgentNotificationReason
  title: string
  body: string | null
  /**
   * Unix epoch milliseconds from the provider event when available.
   */
  occurredAt: bigint
  dedupeKey: string | null
}
