// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAttentionReason } from "./AgentAttentionReason";

export type AgentAttentionEvent = { 
/**
 * PTY session ID. The renderer resolves its owning workspace session.
 */
ptyId: string, reason: AgentAttentionReason, title: string, body: string | null, 
/**
 * Unix epoch milliseconds from the provider event when available.
 */
occurredAt: bigint, dedupeKey: string | null, };
