// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when an agent disconnects from a PTY session
 */
export type AgentDisconnectedEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
}
