// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAlias } from './AgentAlias'

/**
 * On-disk wrapper for the alias store.
 */
export type AgentAliasesStore = { version: number; aliases: Array<AgentAlias> }
