// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextWindowStatus } from './ContextWindowStatus'
import type { CostMetrics } from './CostMetrics'
import type { RateLimits } from './RateLimits'

/**
 * Agent status event with metrics and context window info
 */
export type AgentStatusEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Agent's internal session ID
   */
  agentSessionId: string
  /**
   * Model identifier (e.g., "claude-3-5-sonnet-20241022")
   */
  modelId: string
  /**
   * Human-readable model name
   */
  modelDisplayName: string
  /**
   * Agent version string
   */
  version: string
  /**
   * Context window usage
   */
  contextWindow: ContextWindowStatus
  /**
   * Cost and performance metrics
   */
  cost: CostMetrics
  /**
   * Rate limit status
   */
  rateLimits: RateLimits
}
