// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from './AgentType'

/**
 * Event emitted when an agent is detected in a PTY session
 */
export type AgentDetectedEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Detected agent type
   */
  agentType: AgentType
  /**
   * Process ID of the agent
   */
  pid: number
}
