// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when a Claude transcript reveals the latest user-prompt
 * count.
 *
 * **Duplication note (PR #302 cycle 13 F2):** same restart-boundary
 * duplicate window as `AgentToolCallEvent` — see that struct's doc.
 * Unlike tool-call events, `agent-turn` does NOT have a reliable
 * dedup key in the current schema: `num_turns` is monotonic WITHIN a
 * single Claude invocation but resets to 0 when a new Claude run
 * starts on the same PTY (existing frontend behavior accepts this
 * reset as a legitimate restart). A `(session_id, num_turns)`
 * dedup rule would therefore drop the first turns of post-restart
 * invocations and is unsafe. The duplicate window is bounded to
 * ≤2 events at restart boundaries, so the practical impact is a
 * transient over-count of `num_turns` displayed in the UI — typically
 * invisible because subsequent live turns immediately re-establish
 * the correct count. Adding a stable transcript/agent-session id to
 * the payload (out of scope for PR #302) would enable safe dedup.
 */
export type AgentTurnEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Number of real user prompts observed in this transcript
   */
  numTurns: number
}
