// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-defined alias for launching an agent or arbitrary shell command.
 */
export type AgentAlias = { id: string, alias: string, agent: string, extra: string, account: string | null, };
