// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event emitted when a Claude transcript reveals the latest user-prompt count
 */
export type AgentTurnEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Number of real user prompts observed in this transcript
   */
  numTurns: number
}
