// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPhase } from './AgentPhase'

export type AgentLifecycleEvent = {
  sessionId: string
  /**
   * The agent's own session identity (Claude transcript stem, Codex session_meta.id); lets the bridge drop a stale tail across restart.
   */
  agentSessionId: string
  phase: AgentPhase
}
