// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallStatus } from './ToolCallStatus'

/**
 * Event emitted when an agent executes a tool call
 */
export type AgentToolCallEvent = {
  /**
   * PTY session ID
   */
  sessionId: string
  /**
   * Tool name (e.g., "Read", "Write", "Bash")
   */
  tool: string
  /**
   * Tool call arguments (JSON string)
   */
  args: string
  /**
   * Execution status
   */
  status: ToolCallStatus
  /**
   * ISO 8601 timestamp
   */
  timestamp: string
  /**
   * Execution duration in milliseconds
   */
  durationMs: bigint
}
