// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TitleSource } from './TitleSource'

export type AgentSessionTitleEvent = {
  /**
   * PTY session ID. Same shape as AgentStatusEvent.session_id;
   * the frontend matches on this.
   */
  sessionId: string
  /**
   * Agent's own session UUID (Claude transcript `sessionId` /
   * Codex `session_index.jsonl` `id`). Informational; frontend
   * does not join on this.
   */
  agentSessionId: string
  /**
   * Sanitized title string. Empty string is the explicit "clear"
   * signal; the frontend coerces empty to `agentTitle: undefined`.
   */
  title: string
  /**
   * Where the title came from.
   */
  source: TitleSource
}
