// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { version: number, closeWithNoTabs: string, onLastWindowClosed: string, useSystemPathPrompts: boolean, useSystemPrompts: boolean, redactPrivateValues: boolean, cliOpenBehavior: string, aesthetic: string, accentHue: number, density: string, uiFont: string, monoFont: string, terminalFontFamily: string, reservoirSwell: string, keymapPreset: string, agentShimEnabled: boolean, customKeybindings: { [key in string]?: string }, };
