// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersistedTab } from './PersistedTab'

export type BrowserPane = {
  paneId: string
  paneIndex: number
  active: boolean
  tabs: Array<PersistedTab>
}
