// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Burner foreground-state event (emitted when a burner shell's foreground
 * process changes). `running` is true while a foreground command holds the
 * terminal, false when the shell is idle at its prompt or the platform can't
 * introspect the foreground group.
 */
export type BurnerForegroundEvent = {
  /**
   * Session ID of the burner (ephemeral) PTY
   */
  sessionId: string
  /**
   * Whether a foreground command is currently running in the burner shell
   */
  running: boolean
}
