// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentUsage } from './CurrentUsage'

/**
 * Context window status and token usage
 */
export type ContextWindowStatus = {
  /**
   * Percentage of context window used (0.0-100.0)
   */
  usedPercentage?: number
  /**
   * Percentage of context window remaining (0.0-100.0)
   */
  remainingPercentage: number
  /**
   * Total context window size in tokens
   */
  contextWindowSize: bigint
  /**
   * Total input tokens consumed
   */
  totalInputTokens: bigint
  /**
   * Total output tokens generated
   */
  totalOutputTokens: bigint
  /**
   * Current usage breakdown
   */
  currentUsage?: CurrentUsage
}
