// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cost and performance metrics
 */
export type CostMetrics = {
  /**
   * Total cost in USD. `None` for codex (no cost surface).
   */
  totalCostUsd: number | null
  /**
   * Total session duration in milliseconds
   */
  totalDurationMs: bigint
  /**
   * Total API call duration in milliseconds
   */
  totalApiDurationMs: bigint
  /**
   * Total lines of code added
   */
  totalLinesAdded: bigint
  /**
   * Total lines of code removed
   */
  totalLinesRemoved: bigint
}
