// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cost and performance metrics
 */
export type CostMetrics = {
  /**
   * Total cost in USD. `None` means the agent does not expose cost
   * (e.g. Codex). Serializes to JSON `null`, never absent — so the
   * ts-rs binding intentionally omits `ts(optional)` and the
   * runtime-accurate frontend override in
   * `src/features/agent-status/types/index.ts` types it as
   * `number | null` (not `number?: number`, which would falsely
   * suggest the field could be missing).
   */
  totalCostUsd: number | null
  /**
   * Total session duration in milliseconds
   */
  totalDurationMs: bigint
  /**
   * Total API call duration in milliseconds
   */
  totalApiDurationMs: bigint
  /**
   * Total lines of code added
   */
  totalLinesAdded: bigint
  /**
   * Total lines of code removed
   */
  totalLinesRemoved: bigint
}
