// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current token usage for a single operation
 */
export type CurrentUsage = {
  /**
   * Input tokens used
   */
  inputTokens: bigint
  /**
   * Output tokens generated
   */
  outputTokens: bigint
  /**
   * Cache creation input tokens
   */
  cacheCreationInputTokens: bigint
  /**
   * Cache read input tokens
   */
  cacheReadInputTokens: bigint
}
