// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineType } from './DiffLineType'

/**
 * A single line within a diff hunk
 */
export type DiffLine = {
  type: DiffLineType
  content: string
  oldLineNumber?: number
  newLineNumber?: number
}
