// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Diff line type — variant names match TS `DiffLine.type` via
 * `rename_all = "lowercase"`: `Added` → `"added"`, etc.
 */
export type DiffLineType = 'added' | 'removed' | 'context'
