// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscardScope } from './DiscardScope'

/**
 * Request type for discarding working-tree changes (whole-file or per-hunk).
 */
export type DiscardFileRequest = {
  cwd: string
  path: string
  hunkPatch: string | null
  scope: DiscardScope
}
