// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls which half of the working-tree change `discard_file` removes.
 *
 * - `Unstaged` (default): only the unstaged working-tree edits are reverted
 *   (`git checkout -- <file>` or `git apply -R`).
 * - `Both`: staged changes are also dropped (`git reset HEAD <file>` followed
 *   by the unstaged discard), effectively returning the file to HEAD.
 */
export type DiscardScope = 'unstaged' | 'both'
