// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntryType } from './EntryType'

export type FileEntry = {
  name: string
  type: EntryType
  children?: Array<FileEntry>
}
