// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from './DiffHunk'

/**
 * Parsed diff for a single file — field names match TS `FileDiff` via
 * `rename_all = "camelCase"`: `file_path` → `"filePath"`, etc.
 */
export type FileDiff = {
  filePath: string
  oldPath: string | null
  newPath: string | null
  hunks: Array<DiffHunk>
}
