// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from './FileDiff'

/**
 * Response payload for `get_git_diff` — parsed FileDiff plus the raw
 * before/after file contents that Pierre needs to render via Shiki,
 * plus the raw unified-diff text reused by PR2's `extractHunkPatch`.
 */
export type GetGitDiffResponse = {
  fileDiff: FileDiff
  /**
   * Old file contents at the diff's base (HEAD or index, depending on
   * `staged`). Empty string when the file is untracked or newly added.
   */
  oldText: string
  /**
   * New file contents at the diff's tip (index or working tree).
   * Empty string when the file has been deleted.
   */
  newText: string
  /**
   * The raw unified-diff text. Reused by PR2's `extractHunkPatch()`.
   */
  rawDiff: string
  /**
   * Absolute path of the git repository toplevel (canonicalized). Empty
   * when `cwd` is not inside a git repo. The frontend joins this with the
   * repo-root-relative file path to build an absolute reference an agent
   * can resolve regardless of its own cwd (PR4 inline-feedback dispatch).
   */
  repoRoot: string
}
