// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for killing a PTY session
 */
export type KillPtyRequest = {
  /**
   * Session ID
   */
  sessionId: string
}
