// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Grouping metadata tying a PTY to its owning frontend workspace session,
 * its position in that session's layout, and its detected agent. Persisted
 * in the session cache (`SessionCacheData.groupings`, keyed by PTY id) and
 * surfaced per-PTY on `SessionInfo` so the frontend can reconstruct the
 * original multi-pane layout on restore instead of fragmenting each PTY into
 * its own single-pane session. `None` for any PTY the frontend never grouped
 * (back-compat: restores as a single-pane session, the pre-grouping behavior).
 */
export type PaneGrouping = {
  /**
   * The frontend `Session.id` (an independent React UUID) this PTY belongs
   * to. PTYs sharing this value were panes of one workspace session.
   */
  workspaceSessionId: string
  /**
   * `LayoutId` of the owning workspace: single|vsplit|hsplit|threeRight|quad.
   */
  layout: string
  /**
   * Session-scoped pane id, e.g. `"p0"`.
   */
  paneId: string
  /**
   * Stable pane order within the workspace session.
   */
  paneIndex: number
  /**
   * Detected agent CLI: claude-code|codex|aider|generic.
   */
  agentType: string
  /**
   * Whether this pane is the workspace session's active pane.
   */
  active: boolean
}
