// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY data event payload (emitted to frontend)
 */
export type PtyDataEvent = {
  /**
   * Session ID
   */
  sessionId: string
  /**
   * Output data from PTY stdout
   */
  data: string
  /**
   * Starting byte offset of this chunk in the session's lifetime stream
   */
  offsetStart: bigint
}
