// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY error event payload (emitted on errors)
 */
export type PtyErrorEvent = {
  /**
   * Session ID
   */
  sessionId: string
  /**
   * Error message
   */
  message: string
}
