// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY exit event payload (emitted when process exits)
 */
export type PtyExitEvent = {
  /**
   * Session ID
   */
  sessionId: string
  /**
   * Exit code (if available)
   */
  code: number | null
}
