// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PtyProgressState } from './PtyProgressState'

/**
 * PTY-scoped progress parsed from a live OSC 9;4 report.
 */
export type PtyProgressEvent = {
  /**
   * Session ID
   */
  sessionId: string
  /**
   * Normalized progress state
   */
  state: PtyProgressState
  /**
   * Optional percentage from 0 through 100
   */
  value: number | null
}
