// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalized OSC 9;4 progress state.
 */
export type PtyProgressState =
  | 'remove'
  | 'normal'
  | 'error'
  | 'indeterminate'
  | 'paused'
