// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * PTY session metadata returned after spawning
 */
export type PtySession = {
  /**
   * Unique session identifier
   */
  id: string
  /**
   * Process ID of the shell
   */
  pid: number
  /**
   * Current working directory
   */
  cwd: string
}
