// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitInfo } from './RateLimitInfo'

/**
 * Rate limits for different time windows
 */
export type RateLimits = {
  /**
   * 5-hour rate limit window
   */
  fiveHour: RateLimitInfo
  /**
   * 7-day rate limit window (if applicable)
   */
  sevenDay?: RateLimitInfo
}
