// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rate limit information
 */
export type RateLimitInfo = {
  /**
   * Percentage of rate limit used (0.0-100.0)
   */
  usedPercentage: number
  /**
   * Unix epoch seconds when rate limit resets
   */
  resetsAt: bigint
}
