// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenameAgentSessionErrorReason =
  | 'no-live-agent'
  | 'unsupported-agent'
  | 'empty-title'
  | 'pty-write'
