// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for reorder_sessions command
 */
export type ReorderSessionsRequest = { ids: Array<string> }
