// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for resizing a PTY session
 */
export type ResizePtyRequest = {
  /**
   * Session ID
   */
  sessionId: string
  /**
   * Terminal rows
   */
  rows: number
  /**
   * Terminal columns
   */
  cols: number
}
