// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Scratch foreground-state event (emitted when a scratch shell's foreground
 * process changes). `running` is true while a foreground command holds the
 * terminal, false when the shell is idle at its prompt or the platform can't
 * introspect the foreground group.
 */
export type ScratchForegroundEvent = {
  /**
   * Session ID of the scratch (ephemeral) PTY
   */
  sessionId: string
  /**
   * Whether a foreground command is currently running in the scratch shell
   */
  running: boolean
}
