// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session status — Alive (with replay data) or Exited
 */
export type SessionStatus =
  | {
      kind: 'Alive'
      pid: number
      replay_data: string
      replay_end_offset: bigint
    }
  | { kind: 'Exited'; last_exit_code: number | null }
