// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from './SessionStatus'

/**
 * Single session info returned by list_sessions
 */
export type SessionInfo = { id: string; cwd: string; status: SessionStatus }
