// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionInfo } from './SessionInfo'

/**
 * Response payload for list_sessions command
 */
export type SessionList = {
  activeSessionId: string | null
  sessions: Array<SessionInfo>
}
