// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneGrouping } from './PaneGrouping'
import type { SessionStatus } from './SessionStatus'

/**
 * Single session info returned by list_sessions
 */
export type SessionInfo = {
  id: string
  cwd: string
  shell?: string
  status: SessionStatus
  activityPanelCollapsed?: boolean | null
  /**
   * Workspace grouping for this PTY, or `None` if it was never grouped.
   * `skip_serializing_if = "Option::is_none"` omits the field from the
   * IPC JSON when None instead of emitting `null`, so the generated TS
   * `grouping?: PaneGrouping` accurately matches the runtime shape —
   * a consumer that checks for `undefined` will never see a `null`
   * that the type system claims is `PaneGrouping`.
   */
  grouping?: PaneGrouping
}
