// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for set_active_session command
 */
export type SetActiveSessionRequest = { id: string }
