// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for toggling raw PTY byte emission for a session.
 */
export type SetRawPtyBytesRequest = { 
/**
 * Session ID
 */
sessionId: string, 
/**
 * Whether `pty-data` events should include base64 raw bytes.
 */
enabled: boolean, };
