// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for set_session_activity_panel_collapsed command.
 * `id` is a PTY id — same convention as SetActiveSessionRequest.
 */
export type SetSessionActivityPanelCollapsedRequest = {
  id: string
  collapsed: boolean
}
