// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSessionSnapshot } from './WorkspaceSessionSnapshot'

/**
 * Request payload for set_workspace_sessions — the full current set of
 * workspace sessions and their panes. The backend rebuilds its grouping map
 * from this snapshot (entries for PTYs no longer present are dropped).
 */
export type SetWorkspaceSessionsRequest = {
  sessions: Array<WorkspaceSessionSnapshot>
}
