// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for spawning a new PTY session
 */
export type SpawnPtyRequest = {
  /**
   * Session ID (generated by frontend)
   */
  sessionId: string
  /**
   * Current working directory for the shell
   */
  cwd: string
  /**
   * Optional shell path (defaults to system shell)
   */
  shell?: string
  /**
   * Optional environment variables
   */
  env?: { [key in string]?: string }
}
