// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request type for staging a file (whole-file or per-hunk).
 *
 * Also reused as the request type for `unstage_file` — same fields,
 * same semantics (the handler logic differs, not the request shape).
 */
export type StageFileRequest = {
  cwd: string
  path: string
  /**
   * Unified-diff hunk patch. `None` ⇒ whole-file stage; `Some` ⇒
   * per-hunk stage applied via `git apply --cached`.
   */
  hunkPatch: string | null
}
