// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentType } from './AgentType'

export type TraceUserInteractionRequest = {
  correlationId: string
  spanId: string
  parentSpanId?: string
  event: string
  sessionId?: string
  agentType?: AgentType
  attributes: { [key in string]?: string }
}
