// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for update_session_cwd command
 */
export type UpdateSessionCwdRequest = { id: string; cwd: string }
