// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePaneSnapshot } from './WorkspacePaneSnapshot'

/**
 * One workspace session (a frontend `Session`) in a grouping snapshot.
 */
export type WorkspaceSessionSnapshot = {
  /**
   * The frontend `Session.id` (React UUID).
   */
  id: string
  /**
   * `LayoutId`: single|vsplit|hsplit|threeRight|quad.
   */
  layout: string
  panes: Array<WorkspacePaneSnapshot>
}
