// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserPane } from './BrowserPane'
import type { ShellPane } from './ShellPane'

export type WorkspacePane =
  | ({ kind: 'shell' } & ShellPane)
  | ({ kind: 'browser' } & BrowserPane)
