// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceSession } from './WorkspaceSession'

export type WorkspaceLayoutStore = {
  version: number
  sessions: Array<WorkspaceSession>
}
