// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspacePane } from './WorkspacePane'

export type WorkspaceSession = {
  id: string
  projectId: string
  layout: string
  workingDirectory: string
  active: boolean
  panes: Array<WorkspacePane>
}
