// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One pane within a workspace session snapshot pushed by the frontend.
 */
export type WorkspacePaneSnapshot = {
  /**
   * The PTY id this pane is bound to (frontend `Pane.ptyId`).
   */
  ptyId: string
  /**
   * Session-scoped pane id, e.g. `"p0"`.
   */
  paneId: string
  /**
   * Stable pane order within the workspace session.
   */
  paneIndex: number
  /**
   * Detected agent CLI: claude-code|codex|aider|generic.
   */
  agentType: string
  /**
   * Whether this pane is the workspace session's active pane.
   */
  active: boolean
}
