// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for writing data to a PTY session
 */
export type WritePtyRequest = {
  /**
   * Session ID
   */
  sessionId: string
  /**
   * Data to write to PTY stdin
   */
  data: string
}
