"""Freshness stamp for feature_list.json vs app_spec.md.

Records the hash of the ``app_spec.md`` that produced a given
``feature_list.json`` in a sidecar file. The orchestrator reads the
stamp before trusting an existing feature list so we can detect the
"stale list from a prior run" trap where the harness silently exits
because all features are marked ``passes: true`` against a spec the
user has since replaced.

Why a sidecar and not a field inside ``feature_list.json``: the file
is written by a ``claude -p`` subprocess we don't directly control.
Getting the subprocess to embed a hash would require modifying the
Initializer prompt (more fragile) and would change the feature-list
schema (breaking consumers). The Coordinator can write a sidecar
itself right after the Initializer returns without touching the
Initializer prompt or the feature-list schema.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

STAMP_FILENAME = ".feature_list_stamp.json"


def hash_spec(spec_path: Path) -> str:
    """Return the sha256 hex digest of ``spec_path``'s bytes."""
    return hashlib.sha256(spec_path.read_bytes()).hexdigest()


def write_stamp(project_dir: Path, spec_path: Path) -> None:
    """Record the hash of ``spec_path`` as the generator of the current feature list.

    Call this after a successful Initializer run. The stamp captures the
    exact spec bytes the Initializer consumed — subsequent runs can
    compare and detect drift.

    No-op if ``spec_path`` does not exist (e.g. the Initializer failed
    before reading the spec).
    """
    if not spec_path.exists():
        return

    stamp = {
        "app_spec_hash": hash_spec(spec_path),
        "app_spec_path": spec_path.name,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    (project_dir / STAMP_FILENAME).write_text(
        json.dumps(stamp, indent=2) + "\n"
    )


def read_stamp(project_dir: Path) -> dict | None:
    """Return the stamp dict if present and parseable, else ``None``."""
    stamp_path = project_dir / STAMP_FILENAME
    if not stamp_path.exists():
        return None
    try:
        return json.loads(stamp_path.read_text())
    except (json.JSONDecodeError, OSError):
        return None


def check_stamp_fresh(project_dir: Path, spec_path: Path) -> tuple[bool, str]:
    """Check whether the stamp on disk matches the current spec.

    Returns ``(is_fresh, reason)`` where ``is_fresh`` is True when:
      - the stamp exists
      - AND the stamp's hash matches the current ``spec_path`` content

    ``reason`` is an empty string on freshness, otherwise a
    user-facing explanation of what differs.
    """
    stamp = read_stamp(project_dir)
    if stamp is None:
        return False, (
            f"no {STAMP_FILENAME} found beside feature_list.json. "
            "The feature list was generated by an earlier harness version "
            "or a different run. Re-run the Initializer (delete "
            "feature_list.json and this file) if you want the harness to "
            "trust it against the current app_spec.md."
        )

    if not spec_path.exists():
        return False, (
            f"stamp references {stamp.get('app_spec_path', 'app_spec.md')} "
            "but no such file exists at the project root. "
            "Cannot verify the feature list against a missing spec."
        )

    current_hash = hash_spec(spec_path)
    stamped_hash = stamp.get("app_spec_hash", "")
    if current_hash != stamped_hash:
        return False, (
            f"{spec_path.name} has changed since feature_list.json was "
            f"generated (stamp hash {stamped_hash[:12]}… vs current "
            f"{current_hash[:12]}…). Delete feature_list.json + "
            f"{STAMP_FILENAME} and re-run to regenerate against the "
            "current spec, or pass --ignore-stale-list to proceed anyway."
        )

    return True, ""
