import type { ThemeDefinition } from '../types'

const draculaPalette = {
  bgDark: '#21222c',
  bg: '#282a36',
  bgLow: '#343746',
  bgMid: '#3c4054',
  bgHigh: '#4a4f68',
  comment: '#8a94c8',
  terminalSelection: '#44475a',
  terminalBrightBlack: '#6272a4',
  fg: '#f8f8f2',
  white: '#ffffff',
  red: '#ff5555',
  brightRed: '#ff6e6e',
  green: '#50fa7b',
  brightGreen: '#69ff94',
  yellow: '#f1fa8c',
  brightYellow: '#ffffa5',
  purple: '#bd93f9',
  brightPurple: '#d6acff',
  pink: '#ff79c6',
  brightPink: '#ff92df',
  cyan: '#8be9fd',
  brightCyan: '#a4ffff',
} as const

export const dracula: ThemeDefinition = {
  id: 'dracula',
  label: 'Dracula',
  kind: 'dark',
  ui: {
    surface: draculaPalette.bg,
    'surface-container-lowest': draculaPalette.bgDark,
    'surface-container-low': draculaPalette.bgLow,
    'surface-container': draculaPalette.bgMid,
    'surface-container-high': draculaPalette.bgHigh,
    'surface-container-highest': '#5a6080',
    'surface-bright': '#5a6080',
    'surface-tint': draculaPalette.pink,
    'browser-bar': draculaPalette.bgDark,
    'browser-tab-active': draculaPalette.bgMid,
    primary: draculaPalette.pink,
    'primary-container': '#8a3a70',
    'primary-dim': '#d65bad',
    'primary-deep': '#5f2550',
    'on-primary': draculaPalette.bgDark,
    secondary: draculaPalette.purple,
    'secondary-container': '#6f4bb8',
    'secondary-dim': '#a77bdd',
    'on-secondary': draculaPalette.bgDark,
    'on-secondary-container': draculaPalette.fg,
    tertiary: draculaPalette.cyan,
    'tertiary-container': '#4da7b8',
    'on-tertiary': draculaPalette.bgDark,
    'on-tertiary-container': draculaPalette.bgDark,
    error: draculaPalette.red,
    'error-container': '#a8363a',
    'error-dim': '#d9434b',
    'on-error': draculaPalette.bgDark,
    'on-error-container': draculaPalette.fg,
    success: draculaPalette.green,
    'success-muted': draculaPalette.brightGreen,
    warning: draculaPalette.yellow,
    'on-surface': draculaPalette.fg,
    'on-surface-variant': '#e8e8df',
    'on-surface-muted': draculaPalette.comment,
    outline: '#7d86b8',
    'outline-variant': '#565d7e',
    'editor-fg': draculaPalette.fg,
    'editor-fg-dim': '#e8e8df',
    'vcs-modified': draculaPalette.yellow,
    'vcs-added': draculaPalette.green,
    'vcs-deleted': draculaPalette.red,
    'vcs-renamed': draculaPalette.cyan,
    'vcs-untracked': draculaPalette.pink,
  },
  effects: {
    'glass-fill': 'rgba(40, 42, 54, 0.88)',
    selection: 'rgba(255, 121, 198, 0.25)',
    'scrollbar-thumb': draculaPalette.bgMid,
    'scrollbar-thumb-hover': draculaPalette.comment,
    'diff-added': 'rgba(80, 250, 123, 0.15)',
    'diff-removed': 'rgba(255, 85, 85, 0.15)',
    'diff-highlight-added': 'rgba(80, 250, 123, 0.35)',
    'diff-highlight-removed': 'rgba(255, 85, 85, 0.35)',
    'wash-faint': 'rgba(255, 255, 255, 0.04)',
    'wash-subtle': 'rgba(255, 255, 255, 0.05)',
    'wash-soft': 'rgba(255, 255, 255, 0.08)',
    scrim: '#000000',
  },
  shadows: {
    'pane-focus':
      '0 0 0 6px rgb(255 121 198 / 0.16), 0 8px 32px rgb(0 0 0 / 0.35)',
    modal: '0 24px 80px rgb(0 0 0 / 0.5)',
    'pip-glow': '0 0 4px currentColor',
    ambient: '0 10px 40px rgba(0, 0, 0, 0.4)',
    'glow-primary': '0 0 24px rgba(255, 121, 198, 0.35)',
    'ring-primary': '0 0 0 3px rgba(255, 121, 198, 0.28)',
  },
  syntax: {
    keyword: draculaPalette.pink,
    string: draculaPalette.yellow,
    fn: draculaPalette.green,
    variable: draculaPalette.fg,
    comment: draculaPalette.comment,
    type: draculaPalette.purple,
    tag: draculaPalette.pink,
    class: draculaPalette.cyan,
    operator: draculaPalette.pink,
  },
  terminal: {
    foreground: draculaPalette.fg,
    background: draculaPalette.bg,
    cursor: draculaPalette.fg,
    cursorAccent: draculaPalette.bg,
    selectionBackground: draculaPalette.terminalSelection,
    black: draculaPalette.bgDark,
    red: draculaPalette.red,
    green: draculaPalette.green,
    yellow: draculaPalette.yellow,
    blue: draculaPalette.purple,
    magenta: draculaPalette.pink,
    cyan: draculaPalette.cyan,
    white: draculaPalette.fg,
    brightBlack: draculaPalette.terminalBrightBlack,
    brightRed: draculaPalette.brightRed,
    brightGreen: draculaPalette.brightGreen,
    brightYellow: draculaPalette.brightYellow,
    brightBlue: draculaPalette.brightPurple,
    brightMagenta: draculaPalette.brightPink,
    brightCyan: draculaPalette.brightCyan,
    brightWhite: draculaPalette.white,
  },
  agents: {
    claude: {
      accent: draculaPalette.purple,
      accentDim: 'rgb(189 147 249 / 0.16)',
      accentSoft: 'rgb(189 147 249 / 0.32)',
      onAccent: draculaPalette.bgDark,
    },
    codex: {
      accent: draculaPalette.green,
      accentDim: 'rgb(80 250 123 / 0.16)',
      accentSoft: 'rgb(80 250 123 / 0.32)',
      onAccent: draculaPalette.bgDark,
    },
    shell: {
      accent: draculaPalette.yellow,
      accentDim: 'rgb(241 250 140 / 0.14)',
      accentSoft: 'rgb(241 250 140 / 0.3)',
      onAccent: draculaPalette.bgDark,
    },
    browser: {
      accent: draculaPalette.cyan,
      accentDim: 'rgb(139 233 253 / 0.16)',
      accentSoft: 'rgb(139 233 253 / 0.3)',
      onAccent: draculaPalette.bgDark,
    },
    kimi: {
      accent: draculaPalette.pink,
      accentDim: 'rgb(255 121 198 / 0.16)',
      accentSoft: 'rgb(255 121 198 / 0.32)',
      onAccent: draculaPalette.bgDark,
    },
    opencode: {
      accent: '#ffb86c',
      accentDim: 'rgb(255 184 108 / 0.16)',
      accentSoft: 'rgb(255 184 108 / 0.32)',
      onAccent: draculaPalette.bgDark,
    },
  },
}
