import type { ThemeDefinition } from '../types'

const tokyoNight = {
  bgDark: '#15161e',
  bg: '#1a1b26',
  bgLow: '#1f2335',
  bgMid: '#24283b',
  bgHigh: '#292e42',
  selection: '#283457',
  gutter: '#414868',
  comment: '#565f89',
  fg: '#c0caf5',
  fgDim: '#a9b1d6',
  red: '#f7768e',
  green: '#9ece6a',
  yellow: '#e0af68',
  blue: '#7aa2f7',
  blueDeep: '#3d59a1',
  magenta: '#bb9af7',
  cyan: '#7dcfff',
} as const

export const tokyoNightTheme: ThemeDefinition = {
  id: 'tokyo-night',
  label: 'Tokyo Night',
  kind: 'dark',
  ui: {
    surface: tokyoNight.bgDark,
    'surface-container-lowest': tokyoNight.bgLow,
    'surface-container-low': tokyoNight.bgMid,
    'surface-container': tokyoNight.bgHigh,
    'surface-container-high': tokyoNight.gutter,
    'surface-container-highest': tokyoNight.comment,
    'surface-bright': tokyoNight.comment,
    'surface-tint': tokyoNight.blue,
    'browser-bar': tokyoNight.bgDark,
    'browser-tab-active': tokyoNight.bgMid,
    primary: tokyoNight.blue,
    'primary-container': tokyoNight.blueDeep,
    'primary-dim': '#5f87d7',
    'primary-deep': '#223a66',
    'on-primary': tokyoNight.bgDark,
    secondary: tokyoNight.cyan,
    'secondary-container': '#0db9d7',
    'secondary-dim': '#4aa8cc',
    'on-secondary': tokyoNight.bgDark,
    'on-secondary-container': tokyoNight.bgDark,
    tertiary: tokyoNight.magenta,
    'tertiary-container': '#7e5ab8',
    'on-tertiary': tokyoNight.bgDark,
    'on-tertiary-container': tokyoNight.fg,
    error: tokyoNight.red,
    'error-container': '#db4b4b',
    'error-dim': '#c83e56',
    'on-error': tokyoNight.bgDark,
    'on-error-container': tokyoNight.fg,
    success: tokyoNight.green,
    'success-muted': '#73daca',
    warning: tokyoNight.yellow,
    'on-surface': tokyoNight.fg,
    'on-surface-variant': tokyoNight.fgDim,
    'on-surface-muted': '#7f88b3',
    outline: tokyoNight.gutter,
    'outline-variant': tokyoNight.bgHigh,
    'editor-fg': tokyoNight.fg,
    'editor-fg-dim': tokyoNight.fgDim,
    'vcs-modified': tokyoNight.yellow,
    'vcs-added': tokyoNight.green,
    'vcs-deleted': tokyoNight.red,
    'vcs-renamed': tokyoNight.cyan,
    'vcs-untracked': tokyoNight.magenta,
  },
  effects: {
    'glass-fill': 'rgba(26, 27, 38, 0.88)',
    selection: 'rgba(122, 162, 247, 0.25)',
    'scrollbar-thumb': tokyoNight.bgHigh,
    'scrollbar-thumb-hover': tokyoNight.gutter,
    'diff-added': 'rgba(158, 206, 106, 0.15)',
    'diff-removed': 'rgba(247, 118, 142, 0.15)',
    'diff-highlight-added': 'rgba(158, 206, 106, 0.35)',
    'diff-highlight-removed': 'rgba(247, 118, 142, 0.35)',
    'wash-faint': 'rgba(255, 255, 255, 0.04)',
    'wash-subtle': 'rgba(255, 255, 255, 0.05)',
    'wash-soft': 'rgba(255, 255, 255, 0.08)',
    scrim: '#000000',
  },
  shadows: {
    'pane-focus':
      '0 0 0 6px rgb(122 162 247 / 0.16), 0 8px 32px rgb(0 0 0 / 0.35)',
    modal: '0 24px 80px rgb(0 0 0 / 0.5)',
    'pip-glow': '0 0 4px currentColor',
    ambient: '0 10px 40px rgba(0, 0, 0, 0.4)',
    'glow-primary': '0 0 24px rgba(122, 162, 247, 0.35)',
    'ring-primary': '0 0 0 3px rgba(122, 162, 247, 0.28)',
  },
  syntax: {
    keyword: tokyoNight.magenta,
    string: tokyoNight.green,
    fn: tokyoNight.blue,
    variable: tokyoNight.fgDim,
    comment: tokyoNight.comment,
    type: tokyoNight.yellow,
    tag: tokyoNight.red,
    class: tokyoNight.cyan,
    operator: tokyoNight.cyan,
  },
  terminal: {
    foreground: tokyoNight.fg,
    background: tokyoNight.bg,
    cursor: tokyoNight.fg,
    cursorAccent: tokyoNight.bg,
    selectionBackground: tokyoNight.selection,
    black: tokyoNight.bgDark,
    red: tokyoNight.red,
    green: tokyoNight.green,
    yellow: tokyoNight.yellow,
    blue: tokyoNight.blue,
    magenta: tokyoNight.magenta,
    cyan: tokyoNight.cyan,
    white: tokyoNight.fgDim,
    brightBlack: tokyoNight.gutter,
    brightRed: tokyoNight.red,
    brightGreen: tokyoNight.green,
    brightYellow: tokyoNight.yellow,
    brightBlue: tokyoNight.blue,
    brightMagenta: tokyoNight.magenta,
    brightCyan: tokyoNight.cyan,
    brightWhite: tokyoNight.fg,
  },
  agents: {
    claude: {
      accent: tokyoNight.magenta,
      accentDim: 'rgb(187 154 247 / 0.16)',
      accentSoft: 'rgb(187 154 247 / 0.32)',
      onAccent: tokyoNight.bgDark,
    },
    codex: {
      accent: tokyoNight.green,
      accentDim: 'rgb(158 206 106 / 0.16)',
      accentSoft: 'rgb(158 206 106 / 0.32)',
      onAccent: tokyoNight.bgDark,
    },
    shell: {
      accent: tokyoNight.yellow,
      accentDim: 'rgb(224 175 104 / 0.14)',
      accentSoft: 'rgb(224 175 104 / 0.3)',
      onAccent: tokyoNight.bgDark,
    },
    browser: {
      accent: tokyoNight.cyan,
      accentDim: 'rgb(125 207 255 / 0.16)',
      accentSoft: 'rgb(125 207 255 / 0.3)',
      onAccent: tokyoNight.bgDark,
    },
    kimi: {
      accent: tokyoNight.red,
      accentDim: 'rgb(247 118 142 / 0.16)',
      accentSoft: 'rgb(247 118 142 / 0.32)',
      onAccent: tokyoNight.bgDark,
    },
    opencode: {
      accent: tokyoNight.blue,
      accentDim: 'rgb(122 162 247 / 0.16)',
      accentSoft: 'rgb(122 162 247 / 0.32)',
      onAccent: tokyoNight.bgDark,
    },
  },
}
