//! Type definitions for terminal PTY operations

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// PTY session identifier (UUID string)
pub type SessionId = String;

/// PTY session metadata returned after spawning
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtySession {
    /// Unique session identifier
    pub id: SessionId,
    /// Process ID of the shell
    pub pid: u32,
    /// Current working directory
    pub cwd: String,
}

/// Request payload for spawning a new PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SpawnPtyRequest {
    /// Session ID (generated by frontend)
    pub session_id: SessionId,
    /// Current working directory for the shell
    pub cwd: String,
    /// Optional shell path (defaults to system shell)
    #[cfg_attr(test, ts(optional))]
    pub shell: Option<String>,
    /// Optional environment variables
    #[cfg_attr(test, ts(optional))]
    #[cfg_attr(test, ts(type = "Record<string, string>"))]
    pub env: Option<HashMap<String, String>>,
    /// Generate statusline bridge files for agent status tracking
    #[serde(default)]
    pub enable_agent_bridge: bool,
}

/// Request payload for writing data to a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct WritePtyRequest {
    /// Session ID
    pub session_id: SessionId,
    /// Data to write to PTY stdin
    pub data: String,
}

/// Request payload for resizing a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct ResizePtyRequest {
    /// Session ID
    pub session_id: SessionId,
    /// Terminal rows
    pub rows: u16,
    /// Terminal columns
    pub cols: u16,
}

/// Request payload for killing a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct KillPtyRequest {
    /// Session ID
    pub session_id: SessionId,
}

/// PTY data event payload (emitted to frontend)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyDataEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Output data from PTY stdout
    pub data: String,
    /// Starting byte offset of this chunk in the session's lifetime stream
    pub offset_start: u64,
}

/// PTY exit event payload (emitted when process exits)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyExitEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Exit code (if available)
    pub code: Option<i32>,
}

/// PTY error event payload (emitted on errors)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyErrorEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Error message
    pub message: String,
}

/// Session status — Alive (with replay data) or Exited
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(tag = "kind")]
pub enum SessionStatus {
    Alive {
        pid: u32,
        replay_data: String,
        replay_end_offset: u64,
    },
    Exited {
        last_exit_code: Option<i32>,
    },
}

/// Single session info returned by list_sessions
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SessionInfo {
    pub id: String,
    pub cwd: String,
    pub status: SessionStatus,
}

/// Response payload for list_sessions command
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SessionList {
    pub active_session_id: Option<String>,
    pub sessions: Vec<SessionInfo>,
}

/// Request payload for set_active_session command
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
pub struct SetActiveSessionRequest {
    pub id: String,
}

/// Request payload for reorder_sessions command
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
pub struct ReorderSessionsRequest {
    pub ids: Vec<String>,
}

/// Request payload for update_session_cwd command
#[derive(Debug, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
pub struct UpdateSessionCwdRequest {
    pub id: String,
    pub cwd: String,
}
