//! Type definitions for terminal PTY operations

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// PTY session identifier (UUID string)
pub type SessionId = String;

/// PTY session metadata returned after spawning
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtySession {
    /// Unique session identifier
    pub id: SessionId,
    /// Process ID of the shell
    pub pid: u32,
    /// Current working directory
    pub cwd: String,
}

/// Request payload for spawning a new PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct SpawnPtyRequest {
    /// Session ID (generated by frontend)
    pub session_id: SessionId,
    /// Current working directory for the shell
    pub cwd: String,
    /// Optional shell path (defaults to system shell)
    #[cfg_attr(test, ts(optional))]
    pub shell: Option<String>,
    /// Optional environment variables
    #[cfg_attr(test, ts(optional))]
    pub env: Option<HashMap<String, String>>,
}

/// Request payload for writing data to a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct WritePtyRequest {
    /// Session ID
    pub session_id: SessionId,
    /// Data to write to PTY stdin
    pub data: String,
}

/// Request payload for resizing a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct ResizePtyRequest {
    /// Session ID
    pub session_id: SessionId,
    /// Terminal rows
    pub rows: u16,
    /// Terminal columns
    pub cols: u16,
}

/// Request payload for killing a PTY session
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct KillPtyRequest {
    /// Session ID
    pub session_id: SessionId,
}

/// PTY data event payload (emitted to frontend)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyDataEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Output data from PTY stdout
    pub data: String,
}

/// PTY exit event payload (emitted when process exits)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyExitEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Exit code (if available)
    pub code: Option<i32>,
}

/// PTY error event payload (emitted on errors)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(test, derive(ts_rs::TS))]
#[cfg_attr(test, ts(export))]
#[serde(rename_all = "camelCase")]
pub struct PtyErrorEvent {
    /// Session ID
    pub session_id: SessionId,
    /// Error message
    pub message: String,
}
